/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sportdream_nativec_YUVUtils */

#ifndef _Included_com_sportdream_nativec_YUVUtils
#define _Included_com_sportdream_nativec_YUVUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sportdream_nativec_YUVUtils
 * Method:    NV21Scale
 * Signature: (II[BII[B)V
 */
JNIEXPORT void JNICALL Java_com_sportdream_nativec_YUVUtils_NV21Scale
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
