/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sportdream_nativec_udp */

#ifndef _Included_com_sportdream_nativec_udp
#define _Included_com_sportdream_nativec_udp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sportdream_nativec_udp
 * Method:    init
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_com_sportdream_nativec_udp_init
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_sportdream_nativec_udp
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sportdream_nativec_udp_close
  (JNIEnv *, jobject);

/*
 * Class:     com_sportdream_nativec_udp
 * Method:    sendto
 * Signature: (Ljava/lang/String;S[B)V
 */
JNIEXPORT void JNICALL Java_com_sportdream_nativec_udp_sendto
  (JNIEnv *, jobject, jstring, jshort, jbyteArray);

/*
 * Class:     com_sportdream_nativec_udp
 * Method:    recvfrom
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sportdream_nativec_udp_recvfrom
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
