/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sportdream_DreamSDK_FFmpegEncoder */

#ifndef _Included_com_sportdream_DreamSDK_FFmpegEncoder
#define _Included_com_sportdream_DreamSDK_FFmpegEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sportdream_DreamSDK_FFmpegEncoder
 * Method:    startEncoderNative
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_sportdream_DreamSDK_FFmpegEncoder_startEncoderNative
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_sportdream_DreamSDK_FFmpegEncoder
 * Method:    stopEncoderNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sportdream_DreamSDK_FFmpegEncoder_stopEncoderNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sportdream_DreamSDK_FFmpegEncoder
 * Method:    encodeNative
 * Signature: (J[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_sportdream_DreamSDK_FFmpegEncoder_encodeNative
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
