/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/native_window.h>
#include <android/native_window_jni.h>
/* Header for class com_sportdream_DreamSDK_FFmpegDecoder */

#ifndef _Included_com_sportdream_DreamSDK_FFmpegDecoder
#define _Included_com_sportdream_DreamSDK_FFmpegDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sportdream_DreamSDK_FFmpegDecoder
 * Method:    startNative
 * Signature: (IILjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_sportdream_DreamSDK_FFmpegDecoder_startNative
  (JNIEnv *, jobject, jint, jint, jint,jint,jbyteArray, jobject);

/*
 * Class:     com_sportdream_DreamSDK_FFmpegDecoder
 * Method:    stopNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sportdream_DreamSDK_FFmpegDecoder_stopNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sportdream_DreamSDK_FFmpegDecoder
 * Method:    DecodeFrameNative
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_com_sportdream_DreamSDK_FFmpegDecoder_DecodeFrameNative
  (JNIEnv *, jobject, jint, jbyteArray,jint);

#ifdef __cplusplus
}
#endif
#endif
