platform :ios, '8.0'

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'sportdream' do
	pod 'HyphenateLite'
	pod 'EaseUILite', :git =>'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git', :tag => '3.3.2'
	pod 'RSKImageCropper'
    pod 'QBImagePickerController'
    pod 'Qiniu'
    pod 'PLMediaStreamingKit'
    pod 'GPUImage'
    pod 'CocoaAsyncSocket'
    pod 'NerdyUI'
    pod 'MyLayout'
    pod 'pili-librtmp'
end

